### ISSUE TITLE
Auto-update does not seem to recognise that 2.2 is newer than 2.1.2

### ISSUE THREAD

**Issue by chenzw95** [KunoichiZ/lumaupdate#32]
### What model of system are you using?
- [ ] Old 3DS
- [X] Old 3DS XL
- [ ] 2DS (non-XL)
- [ ] New 3DS
- [ ] New 3DS XL
- [ ] New 2DS XL

### What is your current Luma3DS version?
If you are running an hourly version of Luma3DS, please manually update to a stable version as I will no longer deal with people who are using hourlies.

- [ ] Luma3DS v7.1 + boot9strap v1.0/v1.1
- [ ] Luma3DS v8.0 + boot9strap v1.2+
- [X] Luma3DS v8.1 + boot9strap v1.2+
- [ ] Luma3DS v8.1.1 + boot9strap v1.2+

### What version of Luma Updater are you using?
- [ ] v2.0
- [ ] v2.1
- [ ] v2.1.1
- [X] v2.1.2
- [ ] v2.2

### How are you running Luma Updater?
- [X] .cia
- [ ] .3dsx + HBL/Rosalina

### What problems are you experiencing?
Following continued problems on the Nintendo Homebrew discord server with users attempting to update from Luma3DS 7.1 (see #19) even after the 2.2 release of the updater, I found that the updater does not recognise the current latest version (2.2) as newer than 2.1.2 of the updater.

The log file indicates that the updater is indeed aware that 2.2 is the latest version, but there seems to be an issue with comparing the values (2.2 vs 2.1.2).

### What is the exact error code you are receiving?
_No error_

### Steps to reproduce

1. Launch the updater
2. Allow the updater to check with Github
3. Updater does not recognise that 2.2 is a newer version than 2.1.2.

**Comment by KunoichiZ** [comment]
I don't know why the auto-updater is broken. I'm not sure why the app is not recognizing the newer versions. It could probably be that I'm not uploading a file in the releases that the app needs or something. I'll look into it when I have the time.

**Comment by KunoichiZ** [comment]
I just looked into the files I uploaded versus the files that Hamcha uploaded (I even downloaded and installed Hamcha's v1.4.1 to test and see). I made sure to include all of the same files that Hamcha included.  Worst part is: I haven't modified the source code for autoupdate.cpp for the extraction process other than to make the "3DS" folder lowercase to "3ds" and the location of where to download the files, but that has nothing to do with the CIA version extraction and why that doesn't work. All of the files are named the same, everything is the same besides that small change. 

So unless it's some other issue, I'm not sure what the problem is.
