### ISSUE TITLE
LumaUpdater update failed

### ISSUE THREAD

**Issue by EloittER028** [KunoichiZ/lumaupdate#49]
### What model of system are you using?
- [ ] Old 3DS
- [ ] Old 3DS XL
- [ x] 2DS (non-XL)
- [ ] New 3DS
- [ ] New 3DS XL
- [ ] New 2DS XL

### What is your current Luma3DS version?
If you are running an hourly version of Luma3DS, please manually update to a stable version as I will no longer deal with people who are using hourlies.

- [ ] Luma3DS v7.1 + boot9strap v1.0/v1.1
- [ ] Luma3DS v8.0 + boot9strap v1.2+
- [ ] Luma3DS v8.1 + boot9strap v1.2+
- [x] Luma3DS v8.1.1 + boot9strap v1.2+
- [x ] Luma3DS v9.0 + boot9strap v1.2+
- [ ] Luma3DS v9.1 + boot9strap v1.2+

### What version of Luma Updater are you using?
- [ ] v2.0
- [ ] v2.1
- [ ] v2.1.1
- [ ] v2.1.2
- [ ] v2.2
- [ x] v2.3

### How are you running Luma Updater?
- [x ] .cia
- [ ] .3dsx + HBL/Rosalina

### What problems are you experiencing?
Please tell us what problems you are facing.

When trying to update LumaUpdater to version 2.4 I get : Update failed, Reason for failure: DOWNLOAD FAILED, FATAL: could not get location header for 3xx reply, Ret code: ded92

### What is the exact error code you are receiving?
Please give the exact error code the app gives you.

Ret code: ded92

### Steps to reproduce

1. 
2. 
3.

**Comment by Stob442** [comment]
What model of system are you using?

X  New 3DS XL

What is your current Luma3DS version?

If you are running an hourly version of Luma3DS, please manually update to a stable version as I will no longer deal with people who are using hourlies.

    Luma3DS v9.1 + boot9strap v1.2+

What version of Luma Updater are you using?
    [ x] v2.4

How are you running Luma Updater?

    [x ] .cia
    [x ] .3dsx + HBL/Rosalina

What problems are you experiencing?

Please tell us what problems you are facing.
Got same Error, but i manually installed ver 2.4

Update failed, Reason for failure: DOWNLOAD FAILED, FATAL: could not get location header for 3xx reply, Ret code: ded92
What is the exact error code you are receiving?

Please give the exact error code the app gives you.

Ret code: ded92

**Comment by KunoichiZ** [comment]
I’ll take a look at it.

**Comment by EloittER028** [comment]
Thanks
Envoyé depuis Yahoo Mail pour Android 
 
  Le sam., févr. 29, 2020 à 3:49, Kaoru<notifications@github.com> a écrit :   
I’ll take a look at it.

**Comment by KunoichiZ** [comment]
v2.5 has been released. This should fix this issue. Please manually install v2.5.

**Comment by THBKLOTUS** [comment]
@KunoichiZ as soon as i downloaded and installed the v2.5 CIA, my 3DS theme just went back to the "vanilla" one and all my games disappeared, now when i restart it says COULD NOT DETECT AN SD CARD. THE SOFTWARE ON THE SD CARD COULD NOT BE DISPLAYED, but it was working normally before installing the new version cia :(

**Comment by KunoichiZ** [comment]
@THBKLOTUS That is not a Luma Updater related issue. Please take that elsewhere.

**Comment by soupdebug** [comment]
I nee help please

**Comment by KunoichiZ** [comment]
@soupdebug #53

**Comment by narukaioh** [comment]
@KunoichiZ, how to install manually v2.5? I have the same problem but I don't know how can I install it

**Comment by KunoichiZ** [comment]
@narukaioh Install the cia with FBI or any other cia installer.

**Comment by anitaip98** [comment]
@KunoichiZ 

Hello, I still got the error code too, please help me.
I'm using 3DS XL and currently using Luma Updater v2.3. I choose Update to v2.5 (must restart afterwards), then downloading archive. It said:

Update failed
Something went wrong while trying to update, see screen below for details.
Reason for failure : DOWNLOAD FAILED
---
FATAL: Could not get Location header for 3xx reply
Ret code: ded92

It seems the problem is the same as updating to v2.4 before, right? I understand that the others were having probably the same issue, but I read many sources of this case and the resolution is only to download v2.5. I already downloaded the v2.5 one and install the .cia file type through FBI, but it still not working. I even copy all the .rar items to the SD Card while the one I installed to my console is the .cia one.

Then, I tried to choose not to update, it is written:
Currently installed version is: 10/0/1-e834ec0
There are option to install stable version 10.0.1
So I tried to install stable version, and the same FATAL message appeared.

What if I delete the current Luma and install a new v2.5 version? I'm not really sure how to do it though... I mean, I don't know what should I do. Please take a look on this :( I hope you would come with a new resolution, thank you in advance :)

**Comment by KunoichiZ** [comment]
Install the v2.5 cia with FBI. v2.5 works.

**Comment by anitaip98** [comment]
My FBI currently is v2.6, should I downgrade to v2.5?

**Comment by KunoichiZ** [comment]
@anitaip98 v2.5 of Luma Updater, not FBI.

**Comment by anitaip98** [comment]
Yes I did install Luma Updater v2.5 while using FBI v2.6.
You said to Install the v2.5 cia with FBI v2.5 works, while mine is v2.6.
But it still not working, that's why I asked if they should be in the same version or not (both v2.5).
I tried to find the Luma updater v2.4 but it's gone. I wanted to try to update to v2.4 then v2.5 step by step, I don't know I'm stuck with the Luma updater here :(

**Comment by KunoichiZ** [comment]
@anitaip98 when did I say to use FBI v2.5? You should be using the latest version of FBI to install v2.5 of Luma Updater. Installing v2.4 of Luma Updater will do you no good.

**Comment by rlaphoenix** [comment]
New 2DS XL, Luma 10.2.1, Boot9strap 1.2 (iirc)
Error: Could not obtain update details.

The screen clearly states Luma Updater v2.5, and Luma 10.2.1-c058e3f

It's definitely connected to the internet, and I have rebooted since.

p.s. I'm aware there's no update available, I just wanted to check and see if it can tell me that, considering it has been hit or miss for months now.

p.p.s. After leaving the screen on the error page while typing this out, getting all the information compiled, the homebrew seems to have frozen my 3DS too.
